repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: fmt-backend
        name: just fmt-backend
        entry: just fmt-backend
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      - id: lint-backend
        name: just lint-backend
        entry: just lint-backend
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      - id: typecheck-backend
        name: just typecheck-backend
        entry: just typecheck-backend
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      - id: test-backend
        name: just test-backend
        entry: just test-backend
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
