repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: cd backend && uv run ruff format
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      - id: ruff-check
        name: ruff check
        entry: cd backend && uv run ruff check --fix
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      - id: pyright
        name: pyright
        entry: cd backend && uv run pyright
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      - id: pytest
        name: pytest
        entry: cd backend && uv run pytest test
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
