name: Backend Checks

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-checks.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-checks.yml'

jobs:
  backend-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv pip install --system -e ".[dev]"

      - name: Initialize Django Stubs
        run: |
          PYTHONPATH=src uv run python -c "import django; django.setup(); import django_stubs_ext; django_stubs_ext.monkeypatch()"
        env:
          DJANGO_SETTINGS_MODULE: project.settings

      - name: Ruff Format
        run: uv run ruff format --check .

      - name: Ruff Check
        run: uv run ruff check .

      - name: Pyright
        run: uv run pyright

      - name: Pytest
        run: uv run pytest test
        env:
          DJANGO_SETTINGS_MODULE: project.settings
